name: python CI
# This is a basic workflow to help you get started with Actions

on:
    push:
        branches: [ main ]  # Run the workflow on push events to the main branch
    pull_request:
        branches: [ main ]  # Run the workflow on pull request events targeting the main branch

jobs:
    test:
        runs-on: ubuntu-latest  # The job will run on the latest version of Ubuntu

        steps:
          - name: Checkout repository
            uses: actions/checkout@v2  # Check out the repository code

          - name: Set up Python
            uses: actions/setup-python@v2  # Set up Python environment

          - name: Set up PR Reviewer Bot
            uses: omio-labs/pr-reviewer-bot@v1

            with:
              python-version: '3.x'  # Specify the Python version to use

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip  # Upgrade pip to the latest version
              pip install -r requirements.txt  # Install the dependencies from requirements.txt
              

          - name: Run tests
            run: |
              pytest  # Run the tests using pytest